name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Inspect on docker
      run: docker container inspect $HOSTNAME
    - name: Display payload
      run: echo $GITHUB_EVENT_PATH
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
  container:
    image: sittingonthedock/build-docker:1.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock